# Análise Exploratória de Dados (AED) - Base Varejo
**Aluna:** Maria Victoria Gaggi  
**Curso:** Análise de Dados com Python [T8]  
**Mini-Projeto Avaliativo:** Módulo 1 - Semana 07  
**Objetivo:** Realizar a leitura, o diagnóstico de qualidade, o tratamento e a análise exploratória dos dados de transações do varejo para transformar dados brutos em insights de negócio.

# Sprint 1: Leitura e Diagnóstico

Avaliaremos as dimensões da base, os tipos de dados de cada coluna, a presença de valores ausentes (nulos), linhas totalmente duplicadas e inconsistências textuais (células vazias, espaços extras, variações de maiúsculas e minúsculas e valores ausentes escritos como texto, como `#N/D`).

### 1.1. Carga Automatizada e Importação das Bibliotecas
Para garantir a portabilidade e a execução contínua do projeto em diferentes sessões do Google Colab, foi desenvolvida a função `carregar_base_varejo()`.

A função possui parâmetro e retorno, verificando se o arquivo `Base Varejo.csv` já está presente no ambiente local de execução. Caso não esteja, ela aciona automaticamente a interface de upload do Colab (`files.upload()`) e realiza a leitura utilizando o delimitador ponto e vírgula (`;`), conforme a estrutura original do arquivo.

In [139]:
# Carregando arquivo google colab
import os
import pandas as pd
from google.colab import files

# Função para carregar a base de dados do varejo ***
def carregar_base_varejo(caminho_arquivo = 'Base Varejo.csv'):

  # Verifica se o arquivo já está presente no ambiente
  if not os.path.exists(caminho_arquivo):
    print(f'O arquivo {caminho_arquivo} não foi encontrado automaticamente. Por favor, faça o upload do arquivo.')

    # Carrega o arquivo
    uploaded = files.upload()

    print(f'O arquivo {caminho_arquivo} foi carregado com sucesso!')
  else:
    print(f'O arquivo {caminho_arquivo} já está presente no ambiente')

  # Realiza a leitura do arquivo CSV
  df = pd.read_csv(caminho_arquivo, sep = ';')

  # Retorna o DataFrame carregado
  return df

In [140]:
# --- Executando a função de carga ---
df = carregar_base_varejo()

O arquivo Base Varejo.csv já está presente no ambiente

### 1.2. Inspeção Estrutural (Linhas, Colunas e Amostra)
Nesta subetapa, inspecionamos o volume total de dados brutos e os primeiros registros da base para compreender a granularidade das informações registradas (onde cada linha representa um item adquirido em uma compra realizada por determinado cliente).

In [141]:
total_linhas = df.shape[0]
total_colunas = df.shape[1]


print(f'O total de linhas (registros) é: {total_linhas:,}'.replace(',', '.'))
print(f'O total de colunas é: {total_colunas}')

display(df.head())

O total de linhas (registros) é: 830.000
O total de colunas é: 14

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

### 1.3. Mapeamento de Colunas e Tipos de Dados
Verificamos os tipos de dados atribuídos pelo Pandas a cada variável (`dtypes`). Essa verificação é fundamental para confirmar se os identificadores numéricos e datas foram lidos adequadamente ou se necessitarão de conversões nas etapas seguintes.

In [142]:
print('Nomes das colunas:')
print(df.columns.tolist())
print()
df.info()

Nomes das colunas:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

### 1.4. Diagnóstico de valores ausentes (nulos reais - `NaN`)
Quantidade e percentual de valores nulos em cada coluna. Também identificamos as colunas totalmente vazias.

In [143]:
nulos = df.isnull().sum()
tabela_nulos = pd.DataFrame({'nulos': nulos, '% nulos': (nulos / len(df) * 100).round(2)})
display(tabela_nulos)

# Colunas onde todos os valores são nulos
colunas_vazias = df.columns[df.isnull().all()].tolist()
print(f'Colunas 100% vazias ({len(colunas_vazias)}): {colunas_vazias}')

# Nulos nas demais colunas
nulos_restantes = df.drop(columns=colunas_vazias).isnull().sum().sum()
print(f'Nulos nas demais colunas: {nulos_restantes}')

              nulos  % nulos
DATA              0      0.0
CO_ID             0      0.0
CL_ID             0      0.0
CL_GENERO         0      0.0
CL_EC             0      0.0
CL_FHL            0      0.0
CL_SEG            0      0.0
PR_ID             0      0.0
PR_CAT            0      0.0
PR_NOME           0      0.0
Unnamed: 10  830000    100.0
Unnamed: 11  830000    100.0
Unnamed: 12  830000    100.0
Unnamed: 13  830000    100.0

Colunas 100% vazias (4): ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
Nulos nas demais colunas: 0

### 1.5. Diagnóstico de Linhas Duplicadas
Identificamos a quantidade e o percentual de registros totalmente duplicados na base. Compras diferentes efetuadas pelo mesmo cliente não são consideradas duplicadas; porém, linhas em que todas as variáveis são exatamente idênticas precisam ser contabilizadas. Como a base não possui coluna de quantidade, uma linha repetida pode representar o mesmo produto comprado mais de uma vez na mesma compra, e por isso a decisão de removê-las será tomada na Sprint 2.

In [144]:
qtd_duplicadas = df.duplicated().sum()
pct_duplicadas = qtd_duplicadas / len(df) * 100
print(f'Quantidade de linhas duplicadas: {qtd_duplicadas:,}'.replace(',', '.'))
print(f'Percentual de duplicadas: {pct_duplicadas:.2f}%'.replace('.', ','))

Quantidade de linhas duplicadas: 96.553
Percentual de duplicadas: 11,63%

### 1.6. Diagnóstico de Textos Vazios ou Preenchidos com Espaços
Percorremos todas as colunas de texto para verificar se existem valores vazios, formados apenas por espaços ou com espaços nas extremidades (`.str.strip()`). Registramos as quantidades encontradas, inclusive quando são zero.

In [145]:
colunas_texto = df.select_dtypes(exclude='number').columns

for col in colunas_texto:
    vazios = (df[col].str.strip() == '').sum()
    com_espacos = (df[col] != df[col].str.strip()).sum()
    print(f'{col}: vazios ou só espaços = {vazios} | espaços nas pontas = {com_espacos}')

DATA: vazios ou só espaços = 0 | espaços nas pontas = 0
CL_GENERO: vazios ou só espaços = 0 | espaços nas pontas = 0
CL_SEG: vazios ou só espaços = 0 | espaços nas pontas = 0
PR_CAT: vazios ou só espaços = 0 | espaços nas pontas = 0
PR_NOME: vazios ou só espaços = 0 | espaços nas pontas = 0

### 1.7. Validação de Inconsistências e Valores Únicos em Colunas Textuais
Para identificar inconsistências textuais, contamos os valores únicos de cada coluna de texto e mostramos a distribuição completa das colunas com poucas categorias. Também verificamos variações de maiúsculas e minúsculas e buscamos o valor `#N/D`, que representa um dado ausente escrito como texto e que o `isnull()` não detecta.

In [146]:
colunas_texto = df.select_dtypes(exclude='number').columns

for col in colunas_texto:
  qtd_unicos = df[col].nunique()
  print(f"\nColuna: {col} -> {qtd_unicos} valores únicos")

  # Se tem poucas categorias, mostramos todas com a contagem
  if qtd_unicos <= 10:
    print(df[col].value_counts().to_string())

  # Variações de maiúsculas/minúsculas (ex.: 'Bebidas' e 'BEBIDAS' contariam como 2)
  variacoes = qtd_unicos - df[col].str.strip().str.upper().nunique()
  print(f"Variações de maiúsculas/minúsculas: {variacoes}")

  # Procura o valor '#N/D' (dado ausente escrito como texto)
  qtd_nd = (df[col] == '#N/D').sum()
  print(f"Ocorrências de '#N/D': {qtd_nd}")

Coluna: DATA -> 333 valores únicos
Variações de maiúsculas/minúsculas: 0
Ocorrências de '#N/D': 0

Coluna: CL_GENERO -> 2 valores únicos
CL_GENERO
F    432576
M    397424
Variações de maiúsculas/minúsculas: 0
Ocorrências de '#N/D': 0

Coluna: CL_SEG -> 3 valores únicos
CL_SEG
B    530163
C    232101
A     67736
Variações de maiúsculas/minúsculas: 0
Ocorrências de '#N/D': 0

Coluna: PR_CAT -> 7 valores únicos
PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Variações de maiúsculas/minúsculas: 0
Ocorrências de '#N/D': 3650

Coluna: PR_NOME -> 118 valores únicos
Variações de maiúsculas/minúsculas: 0
Ocorrências de '#N/D': 3650

In [147]:
# Verifica quais produtos (ID e Nome) possuem '#N/D' na categoria
print("\nProdutos afetados pelo valor '#N/D' em PR_CAT:")
produtos_com_problema = df[df['PR_CAT'] == '#N/D'][['PR_ID', 'PR_NOME']].value_counts()
print(produtos_com_problema.to_string())

Produtos afetados pelo valor '#N/D' em PR_CAT:
PR_ID  PR_NOME
107    #N/D       3650

In [148]:
# Textos que não estão totalmente em maiúsculas
for col in colunas_texto:
  qtd_minusculas = (df[col] != df[col].str.upper()).sum()
  print(f"{col}: linhas com letras minúsculas = {qtd_minusculas}")

print()
print(df[df['PR_NOME'] != df['PR_NOME'].str.upper()]['PR_NOME'].value_counts().to_string())

DATA: linhas com letras minúsculas = 0
CL_GENERO: linhas com letras minúsculas = 0
CL_SEG: linhas com letras minúsculas = 0
PR_CAT: linhas com letras minúsculas = 0
PR_NOME: linhas com letras minúsculas = 7320

PR_NOME
REFRIGERANTE LIMaO    7320

**Conclusão - Sprint 1: Leitura e Diagnóstico**


*   **Volume de Dados:** Processamento de 830.000 registros e 14 colunas brutas utilizando o separador ;. Cada linha representa um item adquirido em uma compra realizada por determinado cliente.

*   **Qualidade Estrutural:** Identificação de 4 colunas auxiliares vazias (Unnamed) e zero valores ausentes reconhecidos pelo isnull() nas colunas oficiais de negócio. Porém, existem valores ausentes disfarçados de texto (#N/D), detalhados na validação textual.

*   **Integridade e Duplicadas:** Constatação de 96.553 linhas totalmente duplicadas (11,63%). Como a base não possui coluna de quantidade, uma linha repetida pode representar o mesmo produto comprado mais de uma vez na mesma compra. Por isso, a decisão de removê-las será avaliada na Sprint 2, respeitando a regra de negócio de que compras diferentes do mesmo cliente não são duplicatas.


*   **Validação Textual**: A varredura confirmou a ausência de textos vazios e espaços nas extremidades das colunas. No entanto, foram identificadas duas inconsistências importantes para o tratamento na próxima etapa:   


      1. **Inconsistência de caixa** (maiúsculas/minúsculas): Na coluna `PR_NOME`, foi encontrado o valor `REFRIGERANTE LIMaO` em 7.320 linhas com a letra "a" minúscula, fugindo do padrão em maiúsculas mantido no restante da base.   
      2. **Dados ausentes mascarados**: O valor `#N/D` foi encontrado em 3.650 linhas nas colunas `PR_CAT` e `PR_NOME` (todas associadas ao `PR_ID 107`), representando valores ausentes codificados como texto que não são detectados nativamente pelo isnull(). A estratégia para a padronização do texto e o tratamento desses registros será definida e executada na Sprint 2.

*   **Próximos passos (Sprint 2)**: Remover as 4 colunas Unnamed, decidir o tratamento do `#N/D`, avaliar as duplicadas, padronizar ao menos uma coluna textual e converter `DATA` para o tipo data.

# Sprint 2: Limpeza e Padronização

Nesta etapa tratamos os problemas identificados no diagnóstico da Sprint 1. Cada decisão é justificada com base nos dados encontrados e, ao final, comparamos o diagnóstico antes e depois da limpeza.

| Problema identificado | Decisão | Justificativa |
|---|---|---|
| 4 colunas `Unnamed` 100% vazias | Remover | Não possuem informação de negócio |
| `#N/D` em `PR_CAT` e `PR_NOME` (3.650 linhas) | Preencher com `NAO INFORMADO` | Preserva data, cliente e compra válidos das linhas |
| `REFRIGERANTE LIMaO` com letra minúscula (7.320 linhas) | Padronizar para maiúsculas | Mantém o mesmo formato em toda a coluna |
| Linhas duplicadas (96.553) | Remover | São idênticas em todas as colunas |
| `DATA` lida como texto | Converter para data | Permite análises por período |

### 2.1. Cópia de trabalho
Para poder comparar o diagnóstico antes e depois, preservamos a base bruta em `df_original` e aplicamos todas as alterações em uma cópia chamada `df_limpo`.

In [149]:
df_original = df.copy()
df_limpo = df.copy()

### 2.2. Remoção das colunas vazias
As colunas `Unnamed: 10` a `Unnamed: 13` estão 100% vazias (830.000 nulos cada) e não possuem informação de negócio. Por isso, foram **removidas**, reduzindo a base de 14 para 10 colunas.

In [150]:
colunas_antes = df_limpo.shape[1]

# Remove colunas em que todos os valores são nulos
df_limpo = df_limpo.dropna(axis=1, how='all')

print(f'Colunas antes: {colunas_antes} | depois: {df_limpo.shape[1]}')
print()
print(f'Novas colunas: {df_limpo.columns.tolist()}')

Colunas antes: 14 | depois: 10

Novas colunas: ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

### 2.3. Padronização de texto
Nas colunas textuais categóricas (`CL_GENERO`, `CL_SEG`, `PR_CAT` e `PR_NOME`), removemos espaços nas extremidades e convertemos tudo para maiúsculas. O diagnóstico mostrou apenas uma inconsistência real: `REFRIGERANTE LIMaO` (7.320 linhas), que passa a `REFRIGERANTE LIMAO`. Os demais valores já estavam padronizados e não foram alterados.

In [151]:
colunas_padronizar = ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']

# Remove espaços nas pontas e converte para maiúsculas
for col in colunas_padronizar:
  df_limpo[col] = df_limpo[col].str.strip().str.upper()

# Conferência: a quantidade de linhas deve ser a mesma antes e depois
print('Antes: ', (df_original['PR_NOME'] == 'REFRIGERANTE LIMaO').sum())
print('Depois: ', (df_limpo['PR_NOME'] == 'REFRIGERANTE LIMAO').sum())

Antes:  7320
Depois:  7320

### 2.4. Tratamento de valores `#N/D`
O valor `#N/D` representa um dado ausente escrito como texto e aparece em 3.650 linhas de `PR_CAT` e `PR_NOME`, todas do `PR_ID` 107. Decidimos **preencher** com `NAO INFORMADO` em vez de remover as linhas, porque elas possuem data, cliente e compra válidos, e removê-las distorceria a contagem de compras. Também não inventamos uma categoria para o produto.

In [152]:
colunas_nd = ['PR_CAT', 'PR_NOME']

# Substitui o texto '#N/D' por 'NAO INFORMADO'
df_limpo[colunas_nd] = df_limpo[colunas_nd].replace('#N/D', 'NAO INFORMADO')

print("'#N/D'em PR_CAT:", (df_limpo['PR_CAT'] == '#N/D').sum())
print("'NAO INFORMADO' em PR_CAT:", (df_limpo['PR_CAT'] == 'NAO INFORMADO').sum())

print("\n'#N/D'em PR_NOME:", (df_limpo['PR_NOME'] == '#N/D').sum())
print("'NAO INFORMADO'em PR_NOME:", (df_limpo['PR_NOME'] == 'NAO INFORMADO').sum())

'#N/D'em PR_CAT: 0
'NAO INFORMADO' em PR_CAT: 3650

'#N/D'em PR_NOME: 0
'NAO INFORMADO'em PR_NOME: 3650

### 2.5. Remoção de linhas duplicadas
Foram removidas apenas as linhas **idênticas em todas as colunas** (data, compra, cliente e produto). Compras diferentes do mesmo cliente não foram consideradas duplicadas. Como a base não possui coluna de quantidade, não é possível confirmar se alguma repetição representa o mesmo produto comprado mais de uma vez; essa limitação será registrada nas conclusões.

In [153]:
registros_antes = len(df_limpo)

# Remove linhas duplicadas
df_limpo = df_limpo.drop_duplicates().reset_index(drop=True)

registros_depois = len(df_limpo)

print(f'Linhas antes: {registros_antes:,}'.replace(',', '.'))
print(f'Linhas depois: {registros_depois:,}'.replace(',', '.'))
print(f'Duplicadas removidas: {registros_antes - registros_depois:,}'.replace(',', '.'))

Linhas antes: 830.000
Linhas depois: 733.447
Duplicadas removidas: 96.553

### 2.6. Conversão da coluna `DATA`
A coluna `DATA` foi lida como texto (formato dia/mês/ano). Foi convertida para o tipo data para permitir análises por período.

In [154]:
df_limpo['DATA'] = pd.to_datetime(df_limpo['DATA'], format='%d/%m/%Y')

print('Tipo da coluna DATA antes: ', df_original['DATA'].dtype)
print('Tipo da coluna DATA depois: ', df_limpo['DATA'].dtype)
print()
print('Primeira data:', df_limpo['DATA'].min().date())
print('Última data:', df_limpo['DATA'].max().date())

Tipo da coluna DATA antes:  object
Tipo da coluna DATA depois:  datetime64[ns]

Primeira data: 2019-01-04
Última data: 2022-12-08

### 2.7. Comparação do diagnóstico antes e depois
A tabela abaixo compara a base bruta (`df_original`) com a base tratada (`df_limpo`), mostrando o efeito de cada decisão de limpeza.

*Nota:* As linhas com `REFRIGERANTE LIMAO` passam de 7.320 para 6.451 porque 869 dessas linhas estavam entre as duplicadas removidas na etapa 2.5. Nenhuma linha com "LIMaO" restou na base.

In [155]:
comparacao = pd.DataFrame({
    'Antes': [
        len(df_original),
        df_original.shape[1],
        df_original.isnull().sum().sum(),
        df_original.duplicated().sum(),
        (df_original['PR_CAT'] == '#N/D').sum(),
        (df_original['PR_CAT'] == 'NAO INFORMADO').sum(),
        (df_original['PR_NOME'] == '#N/D').sum(),
        (df_original['PR_NOME'] == 'NAO INFORMADO').sum(),
        (df_original['PR_NOME'] == 'REFRIGERANTE LIMaO').sum(),
        (df_original['PR_NOME'] == 'REFRIGERANTE LIMAO').sum()
    ],
    'Depois': [
        len(df_limpo),
        df_limpo.shape[1],
        df_limpo.isnull().sum().sum(),
        df_limpo.duplicated().sum(),
        (df_limpo['PR_CAT'] == '#N/D').sum(),
        (df_limpo['PR_CAT'] == 'NAO INFORMADO').sum(),
        (df_limpo['PR_NOME'] == '#N/D').sum(),
        (df_limpo['PR_NOME'] == 'NAO INFORMADO').sum(),
        (df_limpo['PR_NOME'] == 'REFRIGERANTE LIMaO').sum(),
        (df_limpo['PR_NOME'] == 'REFRIGERANTE LIMAO').sum()
        ]
},
index=['Registros', 'Colunas', 'Valores nulos (NaN)', 'Linhas duplicadas',
"Ocorrências de '#N/D' em PR_CAT", "Ocorrências de 'NAO INFORMADO' em PR_CAT", "Ocorrências de '#N/D' em PR_NOME", "Ocorrências de 'NAO INFORMADO' em PR_NOME", "Linhas com REFRIGERANTE LIMaO", "Linhas com REFRIGERANTE LIMAO"])

display(comparacao)

                                             Antes  Depois
Registros                                   830000  733447
Colunas                                         14      10
Valores nulos (NaN)                        3320000       0
Linhas duplicadas                            96553       0
Ocorrências de '#N/D' em PR_CAT               3650       0
Ocorrências de 'NAO INFORMADO' em PR_CAT         0    3228
Ocorrências de '#N/D' em PR_NOME              3650       0
Ocorrências de 'NAO INFORMADO' em PR_NOME        0    3228
Linhas com REFRIGERANTE LIMaO                 7320       0
Linhas com REFRIGERANTE LIMAO                    0    6451

**Conclusão - Sprint 2: Limpeza e Padronização**

*Colunas:* Foram removidas as 4 colunas `Unnamed` (100% vazias), reduzindo a base de 14 para 10 colunas.

*Padronização:* Espaços e maiúsculas/minúsculas padronizados nas colunas de texto. A única inconsistência real era `REFRIGERANTE LIMaO` (7.320 linhas), corrigida para `REFRIGERANTE LIMAO`.

*Valores `#N/D`:* As 3.650 ocorrências em `PR_CAT` e `PR_NOME` (`PR_ID` 107) foram preenchidas com `NAO INFORMADO`, preservando as demais informações válidas dessas linhas. Após a remoção das duplicadas, restam 3.228.

*Duplicadas:* Foram removidas 96.553 linhas idênticas em todas as colunas (de 830.000 para 733.447 registros). Como não há coluna de quantidade, parte dessas repetições pode representar o mesmo produto comprado mais de uma vez; essa é uma limitação da análise.

*Data:* A coluna `DATA` foi convertida para o tipo data (de 04/01/2019 a 08/12/2022).

*Próximos passos (Sprint 3):* Transformar o tratamento em funções reutilizáveis (uma para tratar os dados e outra para gerar um resumo).

# Sprint 3: Funções e Organização

Nesta etapa transformamos o tratamento feito na Sprint 2 em funções reutilizáveis, com parâmetros e retorno. Assim, o mesmo processo pode ser aplicado a qualquer base com a mesma estrutura, e o projeto segue uma sequência clara: **leitura → limpeza → análise**.

| Função | Parâmetro | Retorno |
|---|---|---|
| `carregar_base_varejo()` | caminho do arquivo CSV | DataFrame bruto (criada na Sprint 1) |
| `tratar_dados()` | DataFrame bruto e lista de colunas de texto | DataFrame tratado |
| `gerar_resumo()` | DataFrame | Tabela-resumo com os principais indicadores |

### 3.1. Função de tratamento: `tratar_dados()`
A função recebe o DataFrame bruto e aplica as mesmas decisões da Sprint 2, na mesma ordem: remove colunas vazias, padroniza o texto, preenche `#N/D` com `NAO INFORMADO`, remove duplicadas idênticas e converte `DATA` para o tipo data. Ela trabalha sobre uma **cópia** (`.copy()`), por isso o DataFrame original não é alterado, e devolve o DataFrame tratado.

In [156]:
def tratar_dados(df, colunas_texto = ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']):

  # Trabalha em uma cópia para não alterar o DataFrame original
  df_tratado = df.copy()

  # 1. Remove colunas totalmente vazias
  df_tratado = df_tratado.dropna(axis=1, how='all')

  # 2. Padroniza o texto (remove espaços nas pontas e converte para maiúsculas)
  for col in colunas_texto:
    df_tratado[col] = df_tratado[col].str.strip().str.upper()

  # 3. Preenche '#N/D' com 'NAO INFORMADO'
  df_tratado[colunas_texto] = df_tratado[colunas_texto].replace('#N/D', 'NAO INFORMADO')

  # 4. Remove linhas duplicadas
  df_tratado = df_tratado.drop_duplicates().reset_index(drop=True)

  # 5. Converte DATA para o tipo data
  df_tratado['DATA'] = pd.to_datetime(df_tratado['DATA'], format='%d/%m/%Y')


  # Retorna o DataFrame tratado
  return df_tratado

### 3.2. Função de resumo: `gerar_resumo()`
A função recebe um DataFrame (bruto ou tratado) e devolve uma tabela com os principais indicadores. Ela separa o que são **registros** (linhas, ou seja, itens de compra), **compras** (`CO_ID` distintos), **clientes** (`CL_ID` distintos) e **produtos** (`PR_ID` distintos), para evitar confundir essas medidas nas próximas etapas.

In [157]:
def gerar_resumo(df):

  # Converte DATA para data apenas para calcular o período (funciona com a base bruta e a tratada)
  data = pd.to_datetime(df['DATA'], format='%d/%m/%Y')

  # Linhas em que PR_CAT ou PR_NOME têm o valor (cada linha é contada uma vez)
  linhas_nd = ((df['PR_CAT'] == '#N/D') | (df['PR_NOME'] == '#N/D')).sum()
  linhas_nao_informado = ((df['PR_CAT'] == 'NAO INFORMADO') | (df['PR_NOME'] == 'NAO INFORMADO')).sum()

  resumo = {
      'Registros (linhas)': len(df),
      'Colunas': df.shape[1],
      'Valores nulos (NaN)': df.isnull().sum().sum(),
      'Linhas duplicadas': df.duplicated().sum(),
      'Linhas com #N/D': linhas_nd,
      'Linhas com NAO INFORMADO': linhas_nao_informado,
      'Compras distintas (CO_ID)': df['CO_ID'].nunique(),
      'Clientes distintos (CL_ID)': df['CL_ID'].nunique(),
      'Produtos distintos (PR_ID)': df['PR_ID'].nunique(),
      'Primeira data': data.min().date(),
      'Última data': data.max().date()
      }

  # Retorna o resumo como tabela
  return pd.DataFrame.from_dict(resumo, orient='index', columns=['Valor'])

### 3.3. Execução em sequência: leitura, limpeza e resumo
Executamos o fluxo completo a partir da base bruta: carregar, tratar e resumir. Também conferimos que a função `tratar_dados()` produz exatamente o mesmo resultado obtido passo a passo na Sprint 2.

In [158]:
# leitura
df_bruto = carregar_base_varejo()

# limpeza
df_tratado = tratar_dados(df_bruto)

# Resumo antes e depois
resumo_antes = gerar_resumo(df_bruto)
resumo_depois = gerar_resumo(df_tratado)

comparacao_resumo = pd.concat([resumo_antes, resumo_depois], axis=1)
comparacao_resumo.columns = ['Antes', 'Depois']

display(comparacao_resumo)

# Conferência: a função deve gerar o mesmo resultado da Sprint 2
print('\nMesmo resultado da Sprint 2:', df_tratado.equals(df_limpo))

O arquivo Base Varejo.csv já está presente no ambiente

                                 Antes      Depois
Registros (linhas)              830000      733447
Colunas                             14          10
Valores nulos (NaN)            3320000           0
Linhas duplicadas                96553           0
Linhas com #N/D                   3650           0
Linhas com NAO INFORMADO             0        3228
Compras distintas (CO_ID)        18471       18471
Clientes distintos (CL_ID)        1000        1000
Produtos distintos (PR_ID)         229         229
Primeira data               2019-01-04  2019-01-04
Última data                 2022-12-08  2022-12-08

Mesmo resultado da Sprint 2: True

**Conclusão - Sprint 3: Funções e Organização**

*Funções criadas:* `tratar_dados(df, colunas_texto)` recebe a base bruta e devolve a base tratada; `gerar_resumo(df)` recebe uma base e devolve uma tabela de indicadores. Ambas possuem parâmetros e retorno e foram chamadas no fluxo.

*Reprodutibilidade:* A função de tratamento gerou o mesmo resultado obtido passo a passo na Sprint 2 (733.447 registros e 10 colunas), o que permite repetir a limpeza a partir da base original.

*Efeito da limpeza:* Os registros passaram de 830.000 para 733.447, mas o número de compras (18.471), clientes (1.000) e produtos (229) permaneceu igual, indicando que as duplicadas eram linhas repetidas dentro de compras existentes.

*Próximos passos (Sprint 4):* Aplicar um filtro, calcular as estatísticas básicas de uma coluna numérica e produzir dois agrupamentos.