# Análise Exploratória de Dados (AED) - Base Varejo
**Curso:** Análise de Dados com Python [T8]  
**Mini-Projeto Avaliativo:** Módulo 1 - Semana 07  
**Objetivo:** Realizar a leitura, o diagnóstico de qualidade, o tratamento e a análise exploratória dos dados de transações do varejo para transformar dados brutos em insights de negócio.

# Sprint 1: Leitura e Diagnóstico

Nesta primeira etapa, o objetivo é carregar a base de dados bruta (`Base Varejo.csv`) no ambiente de execução do Google Colab e realizar um diagnóstico estrutural inicial. Avaliaremos as dimensões da base, os tipos de dados de cada coluna, a presença de valores ausentes (nulos), linhas totalmente duplicadas e inconsistências textuais (como células vazias ou contendo apenas espaços).

### 1.1. Carga Automatizada e Importação das Bibliotecas
Para garantir a portabilidade e a execução contínua do projeto em diferentes sessões do Google Colab, foi desenvolvida a função `carregar_base_varejo()`.

A função possui parâmetro e retorno, verificando se o arquivo `Base Varejo.csv` já está presente no ambiente local de execução. Caso não esteja, ela aciona automaticamente a interface de upload do Colab (`files.upload()`) e realiza a leitura utilizando o delimitador ponto e vírgula (`;`), conforme a estrutura original do arquivo.

In [22]:
# Carregando arquivo google colab
import os
import pandas as pd
from google.colab import files

# Função para carregar a base de dados do varejo ***
def carregar_base_varejo(caminho_arquivo = 'Base Varejo.csv'):

  # Verifica se o arquivo já está presente no ambiente
  if not os.path.exists(caminho_arquivo):
    print(f'O arquivo {caminho_arquivo} não foi encontrado automaticamente. Por favor, faça o upload do arquivo.')

    # Carrega o arquivo
    uploaded = files.upload()

    print(f'O arquivo {caminho_arquivo} foi carregado com sucesso!')
  else:
    print(f'O arquivo {caminho_arquivo} já está presente no ambiente')

  # Realiza a leitura do arquivo CSV
  df = pd.read_csv(caminho_arquivo, sep = ';')

  # Retorna o DataFrame carregado
  return df

In [23]:
# --- Executando a função de carga ---
df = carregar_base_varejo()

O arquivo Base Varejo.csv já está presente no ambiente

### 1.2. Inspeção Estrutural (Linhas, Colunas e Amostra)
Nesta subetapa, inspecionamos o volume total de dados brutos e os primeiros registros da base para compreender a granularidade das informações registradas (onde cada linha representa um item adquirido em uma compra realizada por determinado cliente).

In [24]:
total_linhas = df.shape[0]
total_colunas = df.shape[1]

print(f'O total de linhas é: {total_linhas}')
print(f'O total de colunas é: {total_colunas}')

O total de linhas é: 830000
O total de colunas é: 14

In [25]:
display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

### 1.3. Mapeamento de Colunas e Tipos de Dados
Verificamos os tipos de dados atribuídos pelo Pandas a cada variável (`dtypes`). Essa verificação é fundamental para confirmar se os identificadores numéricos e datas foram lidos adequadamente ou se necessitarão de conversões nas etapas seguintes.

In [26]:
# Tipos de dados e estrutura
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB
None

In [27]:
# nome colunas
df.columns.tolist()

['DATA',
 'CO_ID',
 'CL_ID',
 'CL_GENERO',
 'CL_EC',
 'CL_FHL',
 'CL_SEG',
 'PR_ID',
 'PR_CAT',
 'PR_NOME',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13']

In [28]:
# tipo de dados
df.dtypes

DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

### 1.4. Diagnóstico de Valores Ausentes (Nulos)
Mapeamos a quantidade de valores nulos (`NaN`) presentes em cada uma das colunas da base de dados bruta.
*(Nota: O registro das colunas nulas identificadas aqui servirá de insumo para o tratamento e remoção de colunas fantasmas na Sprint 2).*

In [29]:
valores_nulos = df.isnull().sum()
print(valores_nulos)

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

### 1.5. Diagnóstico de Linhas Duplicadas
Identificamos a quantidade exata de registros totalmente duplicados na base. Respeitando as regras de negócio do projeto, lembramos que compras diferentes efetuadas pelo mesmo cliente não são consideradas duplicadas; contudo, registros em que todas as variáveis são exatamente idênticas caracterizam duplicidade de lançamento e precisam ser contabilizados.

In [30]:
qtd_duplicadas = df.duplicated().sum()
print(f'Quantidade de duplicadas: {qtd_duplicadas}')

Quantidade de duplicadas: 96553

### 1.6. Diagnóstico de Textos Vazios ou Preenchidos com Espaços
Varremos todas as colunas do tipo textual (`object`) utilizando a remoção de espaços em branco nas extremidades (`.str.strip()`), garantindo que não existam registros contendo apenas strings vazias (`''`), o que poderia mascarar a ausência de dados válidos.

In [31]:
colunas_texto = df.select_dtypes(include=['object']).columns
for col in colunas_texto:
  vazios = df[col].astype(str).str.strip().eq('').sum()
  print(f'Coluna: {col} - Textos vazios ou espaços: {vazios}')

Coluna: DATA - Textos vazios ou espaços: 0
Coluna: CL_GENERO - Textos vazios ou espaços: 0
Coluna: CL_SEG - Textos vazios ou espaços: 0
Coluna: PR_CAT - Textos vazios ou espaços: 0
Coluna: PR_NOME - Textos vazios ou espaços: 0

### 1.7. Validação de Inconsistências e Valores Únicos em Colunas Textuais
Para identificar possíveis inconsistências textuais (como variações de maiúsculas e minúsculas, erros de digitação ou espaços ocultos), inspecionamos os valores únicos presentes nas colunas categóricas da base.

In [32]:
colunas_texto = df.select_dtypes(include=['object']).columns
for col in colunas_texto:
  unicos = df[col].unique()
  print(f"\nColuna: '{col}'")
  print(f"Quantidade de valores únicos: {len(unicos)}")
  print(f"Alguns valores encontrados: {unicos[:10]}")

Coluna: 'DATA'
Quantidade de valores únicos: 333
Alguns valores encontrados: ['01/02/2019' '01/09/2019' '13/01/2019' '19/01/2019' '23/01/2019'
 '29/01/2019' '02/05/2019' '02/06/2019' '02/09/2019' '14/02/2019']

Coluna: 'CL_GENERO'
Quantidade de valores únicos: 2
Alguns valores encontrados: ['M' 'F']

Coluna: 'CL_SEG'
Quantidade de valores únicos: 3
Alguns valores encontrados: ['C' 'B' 'A']

Coluna: 'PR_CAT'
Quantidade de valores únicos: 7
Alguns valores encontrados: ['BEBIDAS' 'HIGIENE' 'ALIMENTOS' 'LIMPEZA' 'ACESSORIOS' 'PET' '#N/D']

Coluna: 'PR_NOME'
Quantidade de valores únicos: 118
Alguns valores encontrados: ['REFRIGERANTE GUARANA' 'REFRIGERANTE OUTROS' 'LENCO UMEDECIDO' 'ABACAXI'
 'LIMPADOR MULTIUSO' 'HASTES FLEXIVEIS' 'MORTADELA' 'AZEITE' 'AMACIANTE'
 'ENERGETICO']

**Conclusão - Sprint 1: Leitura e Diagnóstico**

*Volume de Dados:* Processamento de 830.000 registros e 14 colunas brutas utilizando o separador ;.

*Qualidade Estrutural:* Identificação de 4 colunas auxiliares vazias (Unnamed) e zero valores ausentes nas colunas oficiais de negócio.

*Integridade e Duplicadas:* Constatação de 96.553 linhas totalmente duplicadas (11,63%), que serão tratadas na próxima etapa respeitando a regra de negócio.

*Validação Textual:* A varredura inicial confirmou ausência de strings vazias, preparando os dados para a padronização de maiúsculas, minúsculas e valores únicos na Sprint 2.